skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "5wCX9ek8QyRb4GHr3XPYwz8MseKUbf6pPjR5ZNHhWH9i"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
